-- TQQQ / SOXL Dashboard V2
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.accounts (
  etf text primary key check (etf in ('TQQQ','SOXL')),
  shares numeric not null default 0,
  avg_cost numeric not null default 0,
  cash numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  etf text not null check (etf in ('TQQQ','SOXL')),
  side text not null check (side in ('매수','매도')),
  shares numeric not null default 0,
  price numeric not null default 0,
  amount numeric not null default 0,
  stage text,
  reason text,
  memo text,
  created_at timestamptz not null default now()
);

create index if not exists trades_trade_date_idx on public.trades (trade_date desc);
create index if not exists trades_etf_idx on public.trades (etf);

create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  etf text not null check (etf in ('TQQQ','SOXL')),
  market_ticker text not null,
  market_price numeric,
  market_200ma numeric,
  market_dist numeric,
  etf_price numeric,
  etf_200ma numeric,
  etf_dist numeric,
  stage integer,
  stage_name text,
  target_pct numeric,
  cash_pct numeric,
  emergency integer,
  bubble boolean default false,
  reason text,
  action text,
  created_at timestamptz not null default now(),
  unique (snapshot_date, etf)
);

create index if not exists snapshots_date_idx on public.snapshots (snapshot_date desc);
create index if not exists snapshots_etf_idx on public.snapshots (etf);

insert into public.accounts (etf, shares, avg_cost, cash)
values ('TQQQ', 0, 0, 0), ('SOXL', 0, 0, 0)
on conflict (etf) do nothing;

-- V2 uses the server-side service-role key in Streamlit Secrets.
-- Therefore no public RLS policies are required for this single-user dashboard.
-- If you later move to user authentication, enable RLS and replace this access model.

-- V2.2: atomic trade journal + account update
create or replace function public.record_trade_and_update_account(
  p_trade_date date,
  p_etf text,
  p_side text,
  p_shares numeric,
  p_price numeric,
  p_stage text default null,
  p_reason text default null,
  p_memo text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_shares numeric := 0;
  v_old_avg numeric := 0;
  v_old_cash numeric := 0;
  v_new_shares numeric;
  v_new_avg numeric;
  v_new_cash numeric;
  v_id bigint;
begin
  if p_etf not in ('TQQQ','SOXL') then raise exception 'Invalid ETF'; end if;
  if p_side not in ('매수','매도') then raise exception 'Invalid side'; end if;
  if p_shares <= 0 or p_price <= 0 then raise exception 'Shares and price must be > 0'; end if;

  select shares, avg_cost, cash into v_old_shares, v_old_avg, v_old_cash
  from public.accounts where etf = p_etf for update;

  if p_side = '매수' then
    v_new_shares := v_old_shares + p_shares;
    v_new_avg := case when v_new_shares > 0 then ((v_old_shares*v_old_avg)+(p_shares*p_price))/v_new_shares else 0 end;
    v_new_cash := v_old_cash - (p_shares*p_price);
  else
    if p_shares > v_old_shares then raise exception 'Sell shares exceed current holdings'; end if;
    v_new_shares := v_old_shares - p_shares;
    v_new_avg := case when v_new_shares > 0 then v_old_avg else 0 end;
    v_new_cash := v_old_cash + (p_shares*p_price);
  end if;

  insert into public.trades(trade_date,etf,side,shares,price,amount,stage,reason,memo)
  values(p_trade_date,p_etf,p_side,p_shares,p_price,p_shares*p_price,p_stage,p_reason,p_memo)
  returning id into v_id;

  update public.accounts
  set shares=v_new_shares, avg_cost=v_new_avg, cash=v_new_cash, updated_at=now()
  where etf=p_etf;

  return v_id;
end;
$$;

revoke all on function public.record_trade_and_update_account(date,text,text,numeric,numeric,text,text,text) from public;
