create table if not exists public.strategy_trades (
  id bigint generated by default as identity primary key,
  date date not null,
  ticker text not null,
  type text not null check (type in ('BUY','SELL')),
  shares double precision not null,
  price double precision not null,
  fx_rate double precision default 0,
  fee double precision default 0,
  memo text default '',
  created_at timestamptz default now()
);

alter table public.strategy_trades enable row level security;

create policy "strategy_trades_anon_select"
on public.strategy_trades for select
to anon using (true);

create policy "strategy_trades_anon_insert"
on public.strategy_trades for insert
to anon with check (true);

create policy "strategy_trades_anon_delete"
on public.strategy_trades for delete
to anon using (true);
